dapp/dapps.json

Adds Squid linked to these chains
- cosmos
- osmosis
- assetmantle
- binance
- comdex
- crescent
- evmos
- fetch.ai
- juno
- kava
- kichain
- kujira
- omniflix
- regen
- secret
- stargaze
- umee
No logo provided on https://raw.githubusercontent.com/cosmostation/chainlist/master/dapp/image/squid.png

feat: add Squid to dapps list

---

chain/crescent/assets.json

This PR is to add our NEOK token metadata to Crescent.
Today we moved few NEOKs from EVMOS to Crescent, see: https://www.mintscan.io/crescent/txs/BBAE4CCF54DD36E4AC43486482ADF4C80FD606F376512778013B20228A3F2465?height=6726194
The denom of our token in Crescent is `sha256(transfer/channel-7/erc20/0x655ecB57432CC1370f65e5dc2309588b71b473A9)`
Where:
- `transfer` is the port
- `channel-7` is the channel between Crescent and EVMOS
- `erc20/...` is the address of our token
Our NEOK token is an ERC20 that has been registered as an IBC coin in an [EVMOS Govrnance proposal](https://app.evmos.org/governance?id=144). I made already two PRs to this repo:
- #538 
- #541
I'm not fully sure about the metadata, especially `counter_party.denom`. How to verify it? Also, do I need to do a PR to this repo …

Add NEOK token for Crescent network

---

chain/evmos/assets.json

I already made these other PRs:
- #538
- #541
- #599
Today we:
- Made an IBC transfer of some NEOK coin from EVMOS to Crescent
- Made a transfer in Crescent from one account to another ([see tx](https://www.mintscan.io/crescent/txs/9C84FC67B9B1E99FDA8625ADCB664F24B651AEB3A979783DDFD53A30640C26E6?height=6748081))
- Made an IBC transfer of one NEOK coin from Crescent to EVMOS ([see tx](https://www.mintscan.io/evmos/txs/2AF50D0BA7925878F24FD26D9ADE29B22A267D7AD27D5BC5A15ED296F55F89F7?height=13616425))
The last transfer doesn't show up in the [asset balance of the receiver](https://www.mintscan.io/evmos/account/evmos1m5gusj2k5nyyafd48umx9uxwl327twczn6ge6h). I was wondering that maybe there is some data missing in this registry, and I made this PR. Please note that I'm not fully sure about …

Add NEOK denom for crescent>evmos IBC

---

chain/cosmos/assets.json

This PR adds Stride's stATOM and STRD tokens to display when bridged to the Cosmos Hub. 
The denom trace for STRD can be verified [here](https://lcd-cosmoshub.blockapsis.com/ibc/apps/transfer/v1/denom_traces/6B8A3F5C2AD51CD6171FA41A7E8C35AD594AB69226438DB94450436EA57B3A89), and the denom trace for stATOM can be verified [here](https://lcd-cosmoshub.blockapsis.com/ibc/apps/transfer/v1/denom_traces/B05539B66B72E2739B986B86391E5D08F12B8D5D2C2A7F8F8CF9ADF674DFA231).
Please let me know if anything should be changed, or if there's anything I can help clarify!

Add Stride assets to Cosmos Hub

---

chain/swap.json

The list of supported chains has been changed as the supported chains have changed in Squid Swap.

add supported squid chains

---

chain/osmosis/assets.json

After discussion with Osmosis team, a new IBC client was created raising the trust treshhold to 2/3 for better security.
We created a new client and new connection so we need to modify the information of the asset on Osmosis.

Modify IBC information

---

chain/osmosis/assets.json

Today we have transferred one NEOK token from EVMOS to Osmosis.
https://www.mintscan.io/osmosis/transactions/14560235DAB1AEA3A25BC1165DDE7AF742C6577CBF82B2D07688029EA3646F98
As the token does not show up as an asset on mintscan, we are adding the metadata to handle it.
The PR contains the asset metadata for NEOK tokens going from Evmos to Osmosis.

Integrate NEOK denom for evmos>osmosis

---

chain/injective/assets.json

Denom was calculated with `sha256(transfer/channel-83/erc20/0x655ecB57432CC1370f65e5dc2309588b71b473A9)`
This is the relayer between Evmos and Injective: https://dev.mintscan.io/evmos/relayers/channel-10/injective/channel-83

Add NEOK denom for Evmos > Injective

---

README.md

Folder path in `How to add your token info` doesn't exist. Now points to folder that does exist.

Readme: Update token list uses wrong folder path

---

chain/planq/assets.json

The planq assets.json has an extra comma which is invalid JSON, so this causes issues with JSON parsers.

Fix invalid JSON formatting in planq assets.json

---

chain/osmosis/assets.json

We have migrated the MARS token from the mars-1 network to become a native factory token on neutron-1. This PR updates the Osmosis token list to reflect these changes.
- The old token logo for MARS.old is now greyed out
- The new ibc denom is updated along with the originDenom to reflect the new token details

update MARS assets on osmosis

---

chain/osmosis/assets_2.json

Bulk Update of Osmosis Assets
For context, there was a lengthy discussion between myself and @wannabit-yongjoo about the upcoming changes.
-Unfortunately, due to the order of assets being very different, it's difficult to do a side-by-side comparison of the changes.
-Only the OSMO asset retains the reference to the Cosmostation custom 3D logo, while all others use what the Chain Registry has registered.
-There are 0 cases of enabled being set to false.

Bulk Update of Osmosis Assets (for v2 structure of Assets)

---

chain/osmosis/assets_2.json

Work in progress.
Want to confirm that there is little changed this time.
Chain Names
Still need to update some chain names. Cosmostation API does not include all chain names (orai, bsc, terra classic, etc.)
Coingecko IDs
Adds many CoinGecko IDs, but only where Osmosis Zone considers it canonical. Removes some CoinGecko IDs that don't exist anymore (dig, marble, hope, etc.)

WIP: Bulk Update Osmosis assets_2.json Again

---

chain/osmosis/assets_2.json

After having added chain_name overrides.
This is a direct copy-and-paste from output, and the little difference proves that the generated assets file from Osmosis Labs is compatible with Cosmostation's required format.
There was recently a bulk cleanup at the Chain Registry of Coingecko IDs that no longer exist. That's why many CoinGecko IDs are being removed.
DGN is new, so is being added.
SHIDO is being added back in. Why was it removed?

Update Osmosis assets_2.json (Round 3 of Validating Generated Output)

---

chain/cnho_stables/param_2.json

The previous link has expired and has been replaced with the latest address.

chore: fix 404 status URL

---

chain/osmosis/assets_2.json

IBC channels between AtomOne and Osmosis have been reset yesterday, see here:
- https://github.com/cosmos/chain-registry/pull/5812
- https://github.com/cosmos/chain-registry/pull/5814
Now updating on Mintscan for better UX

Update ATONE token on Osmosis with new IBC channels

---

mintscan/chains/althea/eco_list.json

change "name" to "Althea.Link" (instead of URL).
When the URL is in the title field, it gets auto-capitalized which makes it look a bit funny (like "Https://althea.link" ).

Update eco_list.json for Althea

---

chain/osmosis/assets_2.json

Bulk Update of Osmosis assets_2.json
Adds some of the most recent alloys. Corrects some minor details here and there (formatting, channels, names, etc.).
From a generated script, which is why there are updates all the way from the start to the end.
I suspect the biggest concern for you might be the replacement of URLs to your custom token logo images with the Chain Registry's images. I'd have to adjust the script to retain Mintscan's images and hope that for now it's not a big deal. (In the future I might be able to make it look for all of Mintscan's custom images and to prefer those.)

Bulk Update of Osmosis assets_2.json

---

chain/babylon/cw20_2.json

Adds new token for Union bridged asset to Babylon. The PR consists of a new cw20 for the supported asset

feat: add uniBTC to bbn

---

chain/babylon/cw20_2.json

I noticed that the .union suffix and the "Union bridged" label were removed from other tokens previously.
However, since LBTC was the one that caused the confusion and PR revert, I’ve added them back here just to be safe.
If you'd prefer to remove them for consistency, just let me know and I’ll update the PR accordingly!

feat: add LBTC to bbn

---

chain/babylon/cw20_2.json

Adds new token for Union bridged asset to Babylon. The PR consists of a new cw20 for the supported asset

feat(bbn): add satLBTC.e

---

chain/babylon/cw20_2.json

Adds new token for Union bridged asset to Babylon. The PR consists of a new cw20 for the supported asset

feat(bbn): add satSolvBTC.e

---

.github/workflows/evm_okx.yml
.github/workflows/evm_squid.yml
.github/workflows/json_validate.yml

Bumps checkout to v5 for future-proofing against Node 24 runner updates. Requires runner v2.327.1+. Workflows compile the same.
More info: https://github.com/actions/checkout/releases/tag/v5.0.0

CI: migrate workflows to checkout v5
