cosmostation/chainlist

chain/crescent/assets.json, chain/juno/assets.json, chain/kujira/assets.json, chain/mars-protocol/assets.json
- Added ATOM from Osmosis
- Added axlUSDC from Osmosis
- Added CRE from Cresent
- Added JUNO from Juno
- Added LUNA from Terra
- Added OSMO from Osmosis
- Added MARS from mars-protocol
- Added MARS from mars-protocol
- Added MARS from mars-protocol
=> Added MARS related IBC assets

chain/mars-protocol/assets.json
- Added KUJI ibc token to chain/mars-protocol/asset.json
- Changed `type` of CRE to `ibc`
=> added KUJI to mars-protocol

chain/umee/assets.json
Add Eth, wbtc, usdc, stosmo, bnb, ist, dot, matic, osmo, axl, statom
=> Update Umee Assets 

chain/bitcanna/moniker/bcnavaloper103cx4ludlqd4q9eefamq5erk7tp65kch6pjutw
bcnavaloper103cx4ludlqd4q9eefamq5erk7tp65kch6pjutw.png
=> bcnavaloper103cx4ludlqd4q9eefamq5erk7tp65kch6pjutw

chain/juno/assets.json, chain/kujira/assets.json, chain/migaloo/assets.json, chain/osmosis/assets.json
BLUE is a token to be launched by the lion cub dao. its integration will make it easy for users upon our launch :) and thank you for integrating the CUB token!
=> Request for integration of BLUE token into cosmostation

chain/kava/contract.json
Added two new assets:
- ATOM
- Tether USDT
Edited 4 assets description
- MultiUSDT
- MultiUSDC
- MultiDAI
- MultiWBTC
=> Kava- Added USDT and Atom and edited multichain assets

mintscan/chain-info-social/akash.json
Forum main 이 cosmos로 연결되어 있어 해당 부분을 akash로 변경
=> Update akash.json / Akash main Forum 링크 수정

mintscan/dapp/sommelier/constants.json, mintscan/dapp/stargaze/constants.json, mintscan/dapp/umee/constants.json
For Major Dapps in dashboard page
=> [MINTSCAN-622] id is added in mintscan dapps

chain/nibiru/fee.json, chain/nibiru/param.json
there was a type into fees, with a an extra 0
=> fix nibiru fees

chain/likecoin/fee.json
https://www.mintscan.io/likecoin/proposals/74
The likecoin community has pass a proposal that recommend all gas prices to be increased by 1000x
=> update likecoin fee by 1000x

chain/bostrom/assets.json
JSON files dont support leading commas :(
=> fix JSON: bostrom/assets.json

mintscan/chain-info-social/stargaze.json
=> Stargaze description 수정

mintscan/dapp/neutron/constants.json
=> Update Neutron Apollo constants.json

mintscan/dapp/comdex/constants.json, mintscan/dapp/cosmos/constants.json, mintscan/dapp/evmos/constants.json, mintscan/dapp/injective/constants.json, mintscan/dapp/juno/constants.json, mintscan/dapp/osmosis/constants.json, mintscan/dapp/sommelier/constants.json, mintscan/dapp/stargaze/constants.json, mintscan/dapp/stride/constants.json, mintscan/dapp/terra/constants.json, mintscan/dapp/umee/constants.json
=> add stride to supported chains

mintscan/chain-info-social/haqq-testnet.json, mintscan/chain-info-social/haqq.json
=> Add HAQQ Network

chain/secret/fee.json
mintscan.io/secret/proposals/289
=> Update Secret fees

chain/secret/assets.json, chain/teritori/assets.json
Reflects the changes from 
https://github.com/cosmos/chain-registry/pull/3600
=> Add TORI to Secret | Add SCRT to Teritori

chain/validators.json
=> Update signType from amino to protobuf in validators.json

chain/juno/contract.json, chain/juno/cw20.json
Sorry, there was an error in the previous contract. We have renewed the contract. Thank You
=> Update MRVA Contract

chain/archway/cw721.json
아치웨이 체인에 cw721.json파일을 추가했습니다.
=> Add archway cw721.json

chain/coss/assets.json
Hi, please help merge this pr. Thanks!
=> Add coingecko API ID of coss chain

chain/dydx/assets.json
This adds info for stDYDX held on the dYdX chain.
=> Add stDYDX on DYDX Chain

chain/archway/cw20.json
Corrected the incorrect image file name.
=> Rename the image file in 'archway/cw20.json'

chain/osmosis/assets.json
Add metadata to the osmosis assets for $CROWDP.
Sample IBC transfer:
https://www.mintscan.io/osmosis/tx/E38A2F212DDD2FCB96771D612E8C14636385959BE909A6F2BADF15DAE7173DC4?height=14846934
=> Add osmosis metadata for $CROWDP

chain/injective/assets.json
Removed duplicate injective assets.
=> Delete duplicate injective asset

chain/osmosis/assets.json
adding IBC'ed nRide token specs to the repository
=> Update assets.json -- add nRide token specs

chain/planq/param.json
=> Update param.json -- add EVM Style Address derivation path

chain/joltify/asset.json
This PR aims to update the IBC channels for the IBCed assets on Joltify mainnet.
=> Update IBC channels for assets on Joltify mainnet

wallet_mobile/dapp/dapps.json
Use your staked ARCH tokens as security to access USDC liquidity.
How to get started for stakers 
—————————————————————————
1. [Create](https://www.sudostake.com) your vault.
2. Deposit ARCH tokens into your vault.
3. Stake and manage your ARCH tokens with your favorite validators.
4. Use your vault containing your staked ARCH tokens as security to access USDC liquidity.
How to get started for lenders
—————————————————————————
1. Go to [vault deals](https://www.sudostake.com/liquidity_requests).
2. Lend to any vault of your choice.
3. Track & manage lending positions across vaults.
=> Add sudostake to Dapp list

chain/injective/assets.json, chain/kujira/assets.json, chain/neutron/assets.json
@wannabit-yongjoo A quick follow up to #1754, which used the wrong link for the USDY logo 😄
=> chore: fix USDY logo link

chain/injective/assets.json
- SYN token fro streamswap on injective
- fixing SYN decimals
=> fixing decimals for SYN

chain/fetchai/param.json
Name : "Fetch.ai" to "ASI Alliance"
Desc : add "Formerly Fetch.ai Network"
=> Update FetchAI Props

mintscan/chains/evmos/eco_list.json, mintscan/chains/evmos/major_contract.json
Reformatted & added the Forge DEX token list found at https://github.com/Forge-Trade/tokenlist/blob/main/src/tokenlist.json
Also, added JokeRace & removed StayKing from ecosystem DApps list.
=> Add to the Evmos eco_list & major_contract

chain/terra/assets2.json, chain/tgrade/assets2.json, chain/titan-testnet/assets2.json, chain/titan/assets2.json, chain/umee/assets2.json, chain/unification/assets2.json, chain/ununifi/assets2.json, chain/vidulum/assets2.json, chain/xpla/assets2.json, chain/zeta/assets2.json
=> Update chain list on going

chain/sifchain/assets2.json, chain/sui/assets2.json
Update asset2.json sui & sifchain
=> Update asset2.json sui & sifchain

chain/injective/assets.json
=> Fix $bINJ & $SYN images

.github/workflows/evm_okx.yml, _script/evm_okx/.gitignore, _script/evm_okx/evm_okx.mjs, _script/evm_okx/package.json
okx api를 사용해서 erc20토큰 리스트를 업데이트 하는 깃헙 액션을 추가했습니다.
- 별도의 키 설정이 필요합니다.
=> Add GIthub Action(erc20_okx)

chain/cronos/erc20_2.json
크로노스 erc20_2.json의 decimal을 수정했습니다.
=> fix cronos erc20_2.json

_script/evm_okx/evm_okx.mjs
=> Fix: okx GitHub action

chain/osmosis/assets.json
Add Mantra to Osmosis' legacy assets.json
=> Add Mantra to Osmosis' legacy assets.json

chain/evmos/assets.json
- Add CROWDP ERC20 token asset to evmos assets.json
=> add crowdp erc20 token metadata to evmos assets

chain/base/erc20_2.json
https://basescan.org/address/0x06bee9e7238a331b68d83df3b5b9b16d5dba83ff#readContract
6
=> Axelar ATOM decimals 18 -> 6

.github/workflows/evm_okx.yml, _script/evm_okx/evm_okx.mjs
Add CoinGecko ID mapping for ERC20 assets
- Support inserting new CoinGecko IDs into the market list database
- The functionality to filter added CoinGecko IDs by market capitalization is not included in this implementation but may be introduced in future updates.
=> Add CoinGecko ID mapping for ERC20 assets

chain/archway/param_2.json, chain/comdex/param_2.json, chain/coreum/param_2.json, chain/juno/param_2.json, chain/osmosis/param_2.json, chain/pryzm/param_2.json, chain/quasar/param_2.json, chain/saga/param_2.json, chain/shentu/param_2.json, chain/stargaze/param_2.json, chain/teritori/param_2.json
This PR aims to add Chainroot resources and endpoints to chainlist
=> feat: add Chainroot resources and info

mintscan/README.md, mintscan/chains/README.md
=> chore: fix some typos in README.md

chain/ixo/assets_2.json, chain/ixo/param_2.json
- Updates to the asset name and description.
- Update to the chain_name, about section, and description.
=> Update post chain upgrade

chain/xion/assets_2.json
This PR adds USDC to the XION config for mintscan.
=> feat: add usdc to xion mainnet

chain/dungeon/assets_2.json
=> Add coingecko_id assets_2.json

chain/dungeon/param_2.json
Hello friends! Pls, update fee parrametrs for dungeon chain. We can't send txs, because can't set fee
=> Dungeon chain: update param_2.json

mintscan/README.md, mintscan/chains/README.md, mintscan/chains/kava/major_contract.json
- **"Nuetorn"** → **"Neutron"**  
- **"thumnail"** → **"thumbnail"**
=> Fix spelling errors

chain/osmosis/assets_2.json
Add IBC bridged $SAM token to Osmosis asset list.
=> Add $SAM token to osmosis

chain/bnb-smart-chain/erc20_2.json
fix typo for chain/bnb-smart-chain/erc20_2.json
=> chore:  fix typo

chain/babylon/assets_2.json
This PR adds milkBABY to Babylon's assets
=> feat: add milkBABY to Babylon's assets

chain/cosmos/assets_2.json, chain/osmosis/assets_2.json
Pax Gold bridged via eureka already appearing on:
Cosmos
https://www.mintscan.io/cosmos/assets/ibc/aWJjLzA5RTk1RjU3OTM5RTM0NEVFMzYxMDlBQzQxNzgwQjhBNTFGMUZFMDU0OEE1MjAzQzU5NTc2NzRGRjY0QzBGMjY=
Osmosis
https://www.mintscan.io/osmosis/assets/ibc/aWJjLzBFRjU2MzA1NzZDNjY5NjhFRjA3ODc4NjhDRjA5RkQ4NjZGQUQxMzFCQzE0OEQyNEExNDgzNThBODVGMEVCNjI=
=> Adding Pax Gold (PAXG) bridged via Eureka to Cosmos & Osmosis

wallet_mobile/dapp/dapps.json
Spotted and fixed a few wording hiccups:
posibilities - possibilities
=> polishing docs: error fixes for clarity
